### ISSUE TITLE
Does it work on global internet ? 

### ISSUE THREAD

**Issue by 0Clay01** [EntySec/SeaShell#54]
I just wanna say it’s just work for local internet 
When i send to someone else with different internet it doesnt work even the port i set to 8080 or their port with same ip address it doesnt work…

**Comment by enty8080** [comment]
@0Clay01 Please, stop opening multiple issues with the same topic.

You need to understand how LAN works first. SeaShell Framework can work over global network like any other server-based application. In order to do this you should use packet forwarder like ngrok to forward traffic from local address to global address assigned by ngrok.
